name: Nightly Build Trigger

on:
  push:
    branches:
      - dev
    paths-ignore:
      - "**.md"

jobs:
  trigger-private-pipeline:
    name: Trigger Private Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Get commit title
        id: get_commit_title
        run: |
          echo "commit_message=$(echo "${{ github.event.head_commit.message }}" | head -n 1)" >> $GITHUB_OUTPUT
      - name: Trigger Pipeline Repo
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PIPELINE_PAT }}
          repository: ThePorgs/Pipelines
          event-type: build-pipeline
          client-payload: |
            {
              "sha": "${{ github.sha }}",
              "commit_message": "${{ steps.get_commit_title.outputs.commit_message }}"
            }